version: 2.2.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu1804
configuration: Release
only_commits:
  files:
    - Unmockable/**/*
    - Unmockable.DependencyInjection/**/*
    - Unmockable.Wrap/**/*
    - Unmockable.Intercept/**/*
environment:
  CODECOV_TOKEN: 7b0a3c86-501a-43d0-8e16-ee996773a3ac
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
after_test:
  - bash <(curl -s https://codecov.io/bash)
deploy:
- provider: NuGet
  api_key:
    secure: C1XWdllP3h983mIvodvqrSkPTgZygNPPGjB/p9+bWzvIpQsaS2D1I3/HxqE/2rwS
  on:
    branch: master