version: 3.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu2004
configuration: Release
only_commits:
  files:
    - Unmockable/**/*
    - Unmockable.DependencyInjection/**/*
    - Unmockable.Wrap/**/*
    - Unmockable.Intercept/**/*
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
test_script:
  - dotnet test -s test.runsettings
after_test:
  - dotnet tool restore && dotnet dotnet-stryker

for:
-  
  branches:
    only: 
      - main
      - stryker
  environment:
    CODECOV_TOKEN: 7b0a3c86-501a-43d0-8e16-ee996773a3ac
    STRYKER_DASHBOARD_API_KEY:
      secure: nVeLgEf6Jdls8IC7Gqlfhjr9sL6jvJWBB0ZY77KU4aTKbRIdBnd/dPl0QXI2JKWE
  after_test:
    - curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -t ${CODECOV_TOKEN} -f **/*.cobertura.xml
    - dotnet tool restore && dotnet stryker --reporter dashboard --dashboard-api-key $STRYKER_DASHBOARD_API_KEY -c 4  
  deploy:
  - provider: NuGet
    api_key:
      secure: 6sPnG9susETMj+SCJB7ESTUOoqhVZ6OAO1W+Qb3Y0h+qjCOo5qnbev8l5ISg32hr
    on:
      branch: main