version: 3.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu2004
configuration: Release
only_commits:
  files:
    - Unmockable/**/*
    - Unmockable.DependencyInjection/**/*
    - Unmockable.Wrap/**/*
    - Unmockable.Intercept/**/*
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
after_test:
  - dotnet tool restore && cd Unmockable.Intercept.Tests && dotnet dotnet-stryker

for:
-  
  branches:
    only: 
      - master
  environment:
    CODECOV_TOKEN: 7b0a3c86-501a-43d0-8e16-ee996773a3ac
    STRYKER_DASHBOARD_API_KEY:
      secure: Q9eJLUa7+LuR77kztd8ae81l1anHg6OnC53TP2texciRqb/pr34Pi4bAVKJNMP/X
  after_test:
    - bash <(curl -s https://codecov.io/bash)
    - dotnet tool restore && cd Unmockable.Intercept.Tests && dotnet dotnet-stryker --reporters "['dashboard']" --dashboard-project github.com/Unmockable/Intercept/master
  deploy:
  - provider: NuGet
    api_key:
      secure: y2c/jyVXBMLBd0ffsnuN6XjhjIS7rg1+cIbBgewTR2N6nHxby45w5/0trQYJ5hmR